$axure.loadCurrentPage({
  "url":"测试-2.html",
  "generationDate":new Date(1500892370540.97),
  "isCanvasEnabled":false,
  "variables":["OnLoadVariable"],
  "page":{
    "packageId":"cd9c9178177940d2bdbd1ce629766727",
    "type":"Axure:Page",
    "name":"测试-2",
    "notes":{
},
    "style":{
      "baseStyle":"627587b6038d43cca051c114ac41ad32",
      "pageAlignment":"near",
      "fill":{
        "fillType":"solid",
        "color":0xFFFFFFFF},
      "image":null,
      "imageHorizontalAlignment":"near",
      "imageVerticalAlignment":"near",
      "imageRepeat":"auto",
      "favicon":null,
      "sketchFactor":"0",
      "colorStyle":"appliedColor",
      "fontName":"应用字体",
      "borderWidth":"0"},
    "adaptiveStyles":{
},
    "interactionMap":{
},
    "diagram":{
      "objects":[{
          "id":"433b735186c04224a72c52a548b24608",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "location":{
              "x":30,
              "y":10},
            "size":{
              "width":327,
              "height":580}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"38d20a4133904ceebee4fb1277b14bbc",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":30,
                  "y":10},
                "size":{
                  "width":327,
                  "height":580}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/页面_1/u0.png"}},
{
          "id":"943c1edd222441b2b5d929c6648ca446",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "fill":{
              "fillType":"solid",
              "color":0xFFCCFF33},
            "location":{
              "x":45,
              "y":166},
            "size":{
              "width":305,
              "height":264}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"d0a03766a0534e25ba3f9acb92c9efa2",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fill":{
                  "fillType":"solid",
                  "color":0xFFCCFF33},
                "location":{
                  "x":45,
                  "y":166},
                "size":{
                  "width":305,
                  "height":264}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/测试-1/u2.png"}},
{
          "id":"aacfd5346f3d4a288a478686cf79388c",
          "label":"",
          "type":"button",
          "styleType":"button",
          "visible":true,
          "style":{
            "location":{
              "x":130,
              "y":459},
            "size":{
              "width":100,
              "height":25}},
          "adaptiveStyles":{
},
          "interactionMap":{
            "onClick":{
              "description":"OnClick",
              "cases":[{
                  "description":"用例 1",
                  "isNewIfGroup":false,
                  "actions":[{
                      "action":"linkWindow",
                      "description":"在 当前窗口 打开 测试-3",
                      "target":{
                        "targetType":"page",
                        "url":"测试-3.html",
                        "includeVariables":true},
                      "linkType":"current"}]}]}},
          "tabbable":true},
{
          "id":"51e85f5060b8498c911f11d86b251fbe",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "location":{
              "x":76,
              "y":200},
            "size":{
              "width":243,
              "height":64}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"9b2968f7a79e4f56b6de037df672f5c4",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":76,
                  "y":200},
                "size":{
                  "width":243,
                  "height":64}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"e58dc23323304118ac041bb483a37c3d",
          "label":"",
          "type":"checkbox",
          "styleType":"checkbox",
          "visible":true,
          "style":{
            "location":{
              "x":96,
              "y":303},
            "size":{
              "width":203,
              "height":16}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"e7f622a4c7044584af7abd373f2c5f3a",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":96,
                  "y":303},
                "size":{
                  "width":203,
                  "height":16}},
              "adaptiveStyles":{
}}]},
{
          "id":"a8afd99a9ba6443db88dfc3d3fcba656",
          "label":"",
          "type":"checkbox",
          "styleType":"checkbox",
          "visible":true,
          "style":{
            "location":{
              "x":96,
              "y":277},
            "size":{
              "width":150,
              "height":16}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"10591e426c9a4cab82193d5395c90b97",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":96,
                  "y":277},
                "size":{
                  "width":150,
                  "height":16}},
              "adaptiveStyles":{
}}]},
{
          "id":"0349bc60be3246a0bf32aed4f494c93d",
          "label":"",
          "type":"checkbox",
          "styleType":"checkbox",
          "visible":true,
          "style":{
            "location":{
              "x":96,
              "y":370},
            "size":{
              "width":223,
              "height":16}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"f219cbbc67c74394a8f5b2419f76bd73",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":96,
                  "y":370},
                "size":{
                  "width":223,
                  "height":16}},
              "adaptiveStyles":{
}}]},
{
          "id":"578359d21ac64c6288684d02edb8f6a2",
          "label":"",
          "type":"checkbox",
          "styleType":"checkbox",
          "visible":true,
          "style":{
            "location":{
              "x":96,
              "y":334},
            "size":{
              "width":203,
              "height":16}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"0edff8361bf7454dbb6248978d023334",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":96,
                  "y":334},
                "size":{
                  "width":203,
                  "height":16}},
              "adaptiveStyles":{
}}]},
{
          "id":"7d2853c698014b5381f1830e4440da28",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "location":{
              "x":105,
              "y":104},
            "size":{
              "width":105,
              "height":16}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"1237a31b2adc4e33a676b905079f833b",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":105,
                  "y":104},
                "size":{
                  "width":105,
                  "height":16}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"97d80ecb36a94e84b0f02db8ba657792",
          "label":"",
          "type":"imageBox",
          "styleType":"imageBox",
          "visible":true,
          "style":{
            "location":{
              "x":31,
              "y":10},
            "size":{
              "width":325,
              "height":70}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"49726d3f9d3d4177886361daf09e255a",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":31,
                  "y":10},
                "size":{
                  "width":325,
                  "height":70}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/页面_1/u5.png"}}]}},
  "masters":{
},
  "objectPaths":{
    "433b735186c04224a72c52a548b24608":{
      "scriptId":"u0"},
    "38d20a4133904ceebee4fb1277b14bbc":{
      "scriptId":"u1"},
    "943c1edd222441b2b5d929c6648ca446":{
      "scriptId":"u2"},
    "d0a03766a0534e25ba3f9acb92c9efa2":{
      "scriptId":"u3"},
    "aacfd5346f3d4a288a478686cf79388c":{
      "scriptId":"u4"},
    "51e85f5060b8498c911f11d86b251fbe":{
      "scriptId":"u5"},
    "9b2968f7a79e4f56b6de037df672f5c4":{
      "scriptId":"u6"},
    "e58dc23323304118ac041bb483a37c3d":{
      "scriptId":"u7"},
    "e7f622a4c7044584af7abd373f2c5f3a":{
      "scriptId":"u8"},
    "a8afd99a9ba6443db88dfc3d3fcba656":{
      "scriptId":"u9"},
    "10591e426c9a4cab82193d5395c90b97":{
      "scriptId":"u10"},
    "0349bc60be3246a0bf32aed4f494c93d":{
      "scriptId":"u11"},
    "f219cbbc67c74394a8f5b2419f76bd73":{
      "scriptId":"u12"},
    "578359d21ac64c6288684d02edb8f6a2":{
      "scriptId":"u13"},
    "0edff8361bf7454dbb6248978d023334":{
      "scriptId":"u14"},
    "7d2853c698014b5381f1830e4440da28":{
      "scriptId":"u15"},
    "1237a31b2adc4e33a676b905079f833b":{
      "scriptId":"u16"},
    "97d80ecb36a94e84b0f02db8ba657792":{
      "scriptId":"u17"},
    "49726d3f9d3d4177886361daf09e255a":{
      "scriptId":"u18"}}});