$axure.loadCurrentPage({
  "url":"测试-3.html",
  "generationDate":new Date(1500892370582.97),
  "isCanvasEnabled":false,
  "variables":["OnLoadVariable"],
  "page":{
    "packageId":"8f5324f9c4b5412f89c809813f938b22",
    "type":"Axure:Page",
    "name":"测试-3",
    "notes":{
},
    "style":{
      "baseStyle":"627587b6038d43cca051c114ac41ad32",
      "pageAlignment":"near",
      "fill":{
        "fillType":"solid",
        "color":0xFFFFFFFF},
      "image":null,
      "imageHorizontalAlignment":"near",
      "imageVerticalAlignment":"near",
      "imageRepeat":"auto",
      "favicon":null,
      "sketchFactor":"0",
      "colorStyle":"appliedColor",
      "fontName":"应用字体",
      "borderWidth":"0"},
    "adaptiveStyles":{
},
    "interactionMap":{
},
    "diagram":{
      "objects":[{
          "id":"c16ad79052e640119030ebd888470760",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "location":{
              "x":30,
              "y":10},
            "size":{
              "width":327,
              "height":580}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"e456c5c3519142b1b6e8ca765d788a7e",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":30,
                  "y":10},
                "size":{
                  "width":327,
                  "height":580}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/页面_1/u0.png"}},
{
          "id":"50faf7ccf1694653b218807d2a478417",
          "label":"",
          "type":"button",
          "styleType":"button",
          "visible":true,
          "style":{
            "location":{
              "x":130,
              "y":459},
            "size":{
              "width":100,
              "height":25}},
          "adaptiveStyles":{
},
          "interactionMap":{
            "onClick":{
              "description":"OnClick",
              "cases":[{
                  "description":"用例 1",
                  "isNewIfGroup":false,
                  "actions":[{
                      "action":"linkWindow",
                      "description":"在 当前窗口 打开 结果页面",
                      "target":{
                        "targetType":"page",
                        "url":"结果页面.html",
                        "includeVariables":true},
                      "linkType":"current"}]}]}},
          "tabbable":true},
{
          "id":"99d685f751ba45cdb64239ed94ecd365",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "fill":{
              "fillType":"solid",
              "color":0xFFCCFF33},
            "location":{
              "x":41,
              "y":130},
            "size":{
              "width":305,
              "height":264}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"c1c07e7baf084b4eb86a3aa04160c218",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fill":{
                  "fillType":"solid",
                  "color":0xFFCCFF33},
                "location":{
                  "x":41,
                  "y":130},
                "size":{
                  "width":305,
                  "height":264}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/测试-1/u2.png"}},
{
          "id":"1ee559a2b3d84ceab056838822aa3192",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "location":{
              "x":56,
              "y":140},
            "size":{
              "width":170,
              "height":80}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"5d65dfaf79904b589db07e76fdd4681e",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":56,
                  "y":140},
                "size":{
                  "width":170,
                  "height":80}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"5cd5ac7500e942a3bf3358bf3c3b062e",
          "label":"",
          "type":"checkbox",
          "styleType":"checkbox",
          "visible":true,
          "style":{
            "location":{
              "x":96,
              "y":231},
            "size":{
              "width":150,
              "height":16}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"2ea715e1eaef4ca9875403dd520d613a",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":96,
                  "y":231},
                "size":{
                  "width":150,
                  "height":16}},
              "adaptiveStyles":{
}}]},
{
          "id":"146c91663cc7462b897cf584fedf5325",
          "label":"",
          "type":"checkbox",
          "styleType":"checkbox",
          "visible":true,
          "style":{
            "location":{
              "x":96,
              "y":198},
            "size":{
              "width":150,
              "height":16}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"e1c1e29dd8574da994abec20c6b798b8",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":96,
                  "y":198},
                "size":{
                  "width":150,
                  "height":16}},
              "adaptiveStyles":{
}}]},
{
          "id":"e42319f1b5b3482cbf4f28f91b1e57f9",
          "label":"",
          "type":"checkbox",
          "styleType":"checkbox",
          "visible":true,
          "style":{
            "location":{
              "x":96,
              "y":255},
            "size":{
              "width":173,
              "height":16}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"467b1a3960354f6cb45d036725a5b992",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":96,
                  "y":255},
                "size":{
                  "width":173,
                  "height":16}},
              "adaptiveStyles":{
}}]},
{
          "id":"437968e128d94d0781ae825ca53cf7c1",
          "label":"",
          "type":"checkbox",
          "styleType":"checkbox",
          "visible":true,
          "style":{
            "location":{
              "x":96,
              "y":289},
            "size":{
              "width":183,
              "height":16}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"70f3a02742fe496e928f66b7d7b49d78",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":96,
                  "y":289},
                "size":{
                  "width":183,
                  "height":16}},
              "adaptiveStyles":{
}}]},
{
          "id":"4cfc3e0f62fc403da590eb26b2c264c8",
          "label":"",
          "type":"checkbox",
          "styleType":"checkbox",
          "visible":true,
          "style":{
            "location":{
              "x":96,
              "y":307},
            "size":{
              "width":150,
              "height":16}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"3220770d72f8404786b7deb4559974e5",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":96,
                  "y":307},
                "size":{
                  "width":150,
                  "height":16}},
              "adaptiveStyles":{
}}]},
{
          "id":"70b58fe5a75d46208d1efe1b7d2fa940",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "location":{
              "x":269,
              "y":194},
            "size":{
              "width":8,
              "height":160}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"eb5927a9ccd4456ca82aa4946380492f",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":269,
                  "y":194},
                "size":{
                  "width":8,
                  "height":160}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"8dbba1a4329c4e528200934d5313d1f4",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "location":{
              "x":96,
              "y":94},
            "size":{
              "width":105,
              "height":16}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"b7ad041284494bc88791950a7940b5d4",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":96,
                  "y":94},
                "size":{
                  "width":105,
                  "height":16}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"f4e3d838878246b0b0093e94b1f40d7c",
          "label":"",
          "type":"imageBox",
          "styleType":"imageBox",
          "visible":true,
          "style":{
            "location":{
              "x":30,
              "y":10},
            "size":{
              "width":325,
              "height":70}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"db3b9c1031144417806d609c7dfc8006",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":30,
                  "y":10},
                "size":{
                  "width":325,
                  "height":70}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/页面_1/u5.png"}}]}},
  "masters":{
},
  "objectPaths":{
    "c16ad79052e640119030ebd888470760":{
      "scriptId":"u0"},
    "e456c5c3519142b1b6e8ca765d788a7e":{
      "scriptId":"u1"},
    "50faf7ccf1694653b218807d2a478417":{
      "scriptId":"u2"},
    "99d685f751ba45cdb64239ed94ecd365":{
      "scriptId":"u3"},
    "c1c07e7baf084b4eb86a3aa04160c218":{
      "scriptId":"u4"},
    "1ee559a2b3d84ceab056838822aa3192":{
      "scriptId":"u5"},
    "5d65dfaf79904b589db07e76fdd4681e":{
      "scriptId":"u6"},
    "5cd5ac7500e942a3bf3358bf3c3b062e":{
      "scriptId":"u7"},
    "2ea715e1eaef4ca9875403dd520d613a":{
      "scriptId":"u8"},
    "146c91663cc7462b897cf584fedf5325":{
      "scriptId":"u9"},
    "e1c1e29dd8574da994abec20c6b798b8":{
      "scriptId":"u10"},
    "e42319f1b5b3482cbf4f28f91b1e57f9":{
      "scriptId":"u11"},
    "467b1a3960354f6cb45d036725a5b992":{
      "scriptId":"u12"},
    "437968e128d94d0781ae825ca53cf7c1":{
      "scriptId":"u13"},
    "70f3a02742fe496e928f66b7d7b49d78":{
      "scriptId":"u14"},
    "4cfc3e0f62fc403da590eb26b2c264c8":{
      "scriptId":"u15"},
    "3220770d72f8404786b7deb4559974e5":{
      "scriptId":"u16"},
    "70b58fe5a75d46208d1efe1b7d2fa940":{
      "scriptId":"u17"},
    "eb5927a9ccd4456ca82aa4946380492f":{
      "scriptId":"u18"},
    "8dbba1a4329c4e528200934d5313d1f4":{
      "scriptId":"u19"},
    "b7ad041284494bc88791950a7940b5d4":{
      "scriptId":"u20"},
    "f4e3d838878246b0b0093e94b1f40d7c":{
      "scriptId":"u21"},
    "db3b9c1031144417806d609c7dfc8006":{
      "scriptId":"u22"}}});