$axure.loadCurrentPage({
  "url":"测试-1.html",
  "generationDate":new Date(1500892370503.97),
  "isCanvasEnabled":false,
  "variables":["OnLoadVariable"],
  "page":{
    "packageId":"2ce768f2e4284e2c8d9e59fb51d9658b",
    "type":"Axure:Page",
    "name":"测试-1",
    "notes":{
},
    "style":{
      "baseStyle":"627587b6038d43cca051c114ac41ad32",
      "pageAlignment":"near",
      "fill":{
        "fillType":"solid",
        "color":0xFFFFFFFF},
      "image":null,
      "imageHorizontalAlignment":"near",
      "imageVerticalAlignment":"near",
      "imageRepeat":"auto",
      "favicon":null,
      "sketchFactor":"0",
      "colorStyle":"appliedColor",
      "fontName":"应用字体",
      "borderWidth":"0"},
    "adaptiveStyles":{
},
    "interactionMap":{
},
    "diagram":{
      "objects":[{
          "id":"21b95a0aec3b4e23bca0172969951543",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "location":{
              "x":30,
              "y":10},
            "size":{
              "width":327,
              "height":580}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"44f69ec12d4e47bfa3e4c6fb5b071d35",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":30,
                  "y":10},
                "size":{
                  "width":327,
                  "height":580}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/页面_1/u0.png"}},
{
          "id":"daae5e2a5a1442b9a952aa849d843e8f",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "fill":{
              "fillType":"solid",
              "color":0xFFCCFF33},
            "location":{
              "x":45,
              "y":166},
            "size":{
              "width":305,
              "height":264}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"ec7849b4d476400c95997c6fc6d593f6",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fill":{
                  "fillType":"solid",
                  "color":0xFFCCFF33},
                "location":{
                  "x":45,
                  "y":166},
                "size":{
                  "width":305,
                  "height":264}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/测试-1/u2.png"}},
{
          "id":"74645607acc143f497a3c76c7c3867ee",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "location":{
              "x":100,
              "y":114},
            "size":{
              "width":105,
              "height":16}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"b914164cc3a64674842851d01510851f",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":100,
                  "y":114},
                "size":{
                  "width":105,
                  "height":16}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"12b29fa8cb544ae898aaabb714c1e96c",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "location":{
              "x":60,
              "y":176},
            "size":{
              "width":170,
              "height":80}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"ac004f96b4614a9d89ab86789614a8c6",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":60,
                  "y":176},
                "size":{
                  "width":170,
                  "height":80}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"fd7d6f98358e41479f4c82b593e4490f",
          "label":"",
          "type":"checkbox",
          "styleType":"checkbox",
          "visible":true,
          "style":{
            "location":{
              "x":100,
              "y":265},
            "size":{
              "width":150,
              "height":16}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"7fb167ff17fb4ea494d9f78888e333e9",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":100,
                  "y":265},
                "size":{
                  "width":150,
                  "height":16}},
              "adaptiveStyles":{
}}]},
{
          "id":"3678a6d2f7fd42c381137e9a4b6e8fe5",
          "label":"",
          "type":"checkbox",
          "styleType":"checkbox",
          "visible":true,
          "style":{
            "location":{
              "x":100,
              "y":234},
            "size":{
              "width":150,
              "height":16}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"fbbfc272ed6d4407ab1f3d7bf0531271",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":100,
                  "y":234},
                "size":{
                  "width":150,
                  "height":16}},
              "adaptiveStyles":{
}}]},
{
          "id":"3a8096b868124f6dac6e89b1a2789e12",
          "label":"",
          "type":"checkbox",
          "styleType":"checkbox",
          "visible":true,
          "style":{
            "location":{
              "x":100,
              "y":284},
            "size":{
              "width":150,
              "height":16}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"5296db11370f44f0971053e84186a7f8",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":100,
                  "y":284},
                "size":{
                  "width":150,
                  "height":16}},
              "adaptiveStyles":{
}}]},
{
          "id":"21c3649b91f544a59a469d69ddf4ca03",
          "label":"",
          "type":"checkbox",
          "styleType":"checkbox",
          "visible":true,
          "style":{
            "location":{
              "x":100,
              "y":314},
            "size":{
              "width":150,
              "height":16}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"f842ff74e0a24c378fe67c567e0a74d3",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":100,
                  "y":314},
                "size":{
                  "width":150,
                  "height":16}},
              "adaptiveStyles":{
}}]},
{
          "id":"41e4b1e9828a4f0199b0ccebeb350e29",
          "label":"",
          "type":"checkbox",
          "styleType":"checkbox",
          "visible":true,
          "style":{
            "location":{
              "x":100,
              "y":345},
            "size":{
              "width":150,
              "height":16}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"4b1a025cd98d40ccb8049047bd86b856",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":100,
                  "y":345},
                "size":{
                  "width":150,
                  "height":16}},
              "adaptiveStyles":{
}}]},
{
          "id":"b231c84693d24871b952aba17f6a1488",
          "label":"",
          "type":"checkbox",
          "styleType":"checkbox",
          "visible":true,
          "style":{
            "location":{
              "x":100,
              "y":374},
            "size":{
              "width":150,
              "height":16}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"ca937fc19a8d4839af473e8bb1f96206",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":100,
                  "y":374},
                "size":{
                  "width":150,
                  "height":16}},
              "adaptiveStyles":{
}}]},
{
          "id":"502c5810c44c4dc78d76185462aea0e7",
          "label":"",
          "type":"checkbox",
          "styleType":"checkbox",
          "visible":true,
          "style":{
            "location":{
              "x":100,
              "y":410},
            "size":{
              "width":150,
              "height":16}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"705db8ce88b74dcfabdcd0cfb2a09279",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":100,
                  "y":410},
                "size":{
                  "width":150,
                  "height":16}},
              "adaptiveStyles":{
}}]},
{
          "id":"117b8c06408743eabb0dcedf04622582",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "location":{
              "x":116,
              "y":494},
            "size":{
              "width":32,
              "height":16}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"5c24a7459f504cdab9d0ab9c61d61f57",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":116,
                  "y":494},
                "size":{
                  "width":32,
                  "height":16}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"716599d66f234ffabeea4db9f30ef81e",
          "label":"",
          "type":"button",
          "styleType":"button",
          "visible":true,
          "style":{
            "location":{
              "x":130,
              "y":459},
            "size":{
              "width":100,
              "height":25}},
          "adaptiveStyles":{
},
          "interactionMap":{
            "onClick":{
              "description":"OnClick",
              "cases":[{
                  "description":"用例 1",
                  "isNewIfGroup":false,
                  "actions":[{
                      "action":"linkWindow",
                      "description":"在 当前窗口 打开 测试-2",
                      "target":{
                        "targetType":"page",
                        "url":"测试-2.html",
                        "includeVariables":true},
                      "linkType":"current"}]}]}},
          "tabbable":true},
{
          "id":"0ceacf9d3364405792f4da137bf9151c",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "location":{
              "x":222,
              "y":233},
            "size":{
              "width":8,
              "height":208}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"5df7e718600b4790b3df7a966cd15b8c",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":222,
                  "y":233},
                "size":{
                  "width":8,
                  "height":208}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"b4308a2648944ae5aa323bf727b2e4e0",
          "label":"",
          "type":"imageBox",
          "styleType":"imageBox",
          "visible":true,
          "style":{
            "location":{
              "x":30,
              "y":10},
            "size":{
              "width":325,
              "height":70}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"526813060f9f46de9df986e0d25329f7",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":30,
                  "y":10},
                "size":{
                  "width":325,
                  "height":70}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/页面_1/u5.png"}}]}},
  "masters":{
},
  "objectPaths":{
    "21b95a0aec3b4e23bca0172969951543":{
      "scriptId":"u0"},
    "44f69ec12d4e47bfa3e4c6fb5b071d35":{
      "scriptId":"u1"},
    "daae5e2a5a1442b9a952aa849d843e8f":{
      "scriptId":"u2"},
    "ec7849b4d476400c95997c6fc6d593f6":{
      "scriptId":"u3"},
    "74645607acc143f497a3c76c7c3867ee":{
      "scriptId":"u4"},
    "b914164cc3a64674842851d01510851f":{
      "scriptId":"u5"},
    "12b29fa8cb544ae898aaabb714c1e96c":{
      "scriptId":"u6"},
    "ac004f96b4614a9d89ab86789614a8c6":{
      "scriptId":"u7"},
    "fd7d6f98358e41479f4c82b593e4490f":{
      "scriptId":"u8"},
    "7fb167ff17fb4ea494d9f78888e333e9":{
      "scriptId":"u9"},
    "3678a6d2f7fd42c381137e9a4b6e8fe5":{
      "scriptId":"u10"},
    "fbbfc272ed6d4407ab1f3d7bf0531271":{
      "scriptId":"u11"},
    "3a8096b868124f6dac6e89b1a2789e12":{
      "scriptId":"u12"},
    "5296db11370f44f0971053e84186a7f8":{
      "scriptId":"u13"},
    "21c3649b91f544a59a469d69ddf4ca03":{
      "scriptId":"u14"},
    "f842ff74e0a24c378fe67c567e0a74d3":{
      "scriptId":"u15"},
    "41e4b1e9828a4f0199b0ccebeb350e29":{
      "scriptId":"u16"},
    "4b1a025cd98d40ccb8049047bd86b856":{
      "scriptId":"u17"},
    "b231c84693d24871b952aba17f6a1488":{
      "scriptId":"u18"},
    "ca937fc19a8d4839af473e8bb1f96206":{
      "scriptId":"u19"},
    "502c5810c44c4dc78d76185462aea0e7":{
      "scriptId":"u20"},
    "705db8ce88b74dcfabdcd0cfb2a09279":{
      "scriptId":"u21"},
    "117b8c06408743eabb0dcedf04622582":{
      "scriptId":"u22"},
    "5c24a7459f504cdab9d0ab9c61d61f57":{
      "scriptId":"u23"},
    "716599d66f234ffabeea4db9f30ef81e":{
      "scriptId":"u24"},
    "0ceacf9d3364405792f4da137bf9151c":{
      "scriptId":"u25"},
    "5df7e718600b4790b3df7a966cd15b8c":{
      "scriptId":"u26"},
    "b4308a2648944ae5aa323bf727b2e4e0":{
      "scriptId":"u27"},
    "526813060f9f46de9df986e0d25329f7":{
      "scriptId":"u28"}}});